### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by phantasyy** [rprichard/logitech-g400-config#2]
python logitech-g400-config.py set -rRATE 1000
Traceback (most recent call last):
  File "logitech-g400-config.py", line 138, in <module>
    main()
  File "logitech-g400-config.py", line 126, in main
    do_set_cmd(subargs)
  File "logitech-g400-config.py", line 87, in do_set_cmd
    dev = open_device()
  File "logitech-g400-config.py", line 59, in open_device
    return hid.Device(path=info_good[0]["path"])
  File "/home/andreas/Downloads/logitech-g400-config-master/hid/__init__.py", line 96, in __init__
    raise HIDException('unable to open device')
hid.HIDException: unable to open device

**Comment by asundell** [comment]
Ensure you're running either with sudo or using the security instructions. I had an identical error until I ran it with sudo.

**Comment by rprichard** [comment]
I should add a note to the security instructions:  The udev rule only applies as the device is plugged in.  If your mouse is plugged in when you add the rule, you'll need to unplug in and plug it back in.

**Comment by phantasyy** [comment]
I did run it with sudo. Also are you saying I should unplug the mouse after executing **set -rRATE 1000**  and then plug it back in?

Here is what I got running it with sudo to check the settings.

sudo python logitech-g400-config.py 
sampling_rate: 1000
dpi_level: 3600


And here is what I got from attempting to set a option.

 sudo python logitech-g400-config.py set -rRATE 1000
usage: logitech-g400-config.py [show]
  Prints the current mouse settings

usage: logitech-g400-config.py set [options]
  -rRATE
    RATE is in Hz and is one of: 125, 250, 500, or 1000.  The Windows driver
    defaults to 500 Hz.
  -dDPI
    DPI is one of: 400, 800, 1800, 3600, or 3600_frozen.  With 3600_frozen, the
    DPI+/DPI- buttons no longer change the DPI and instead are treated as
    any other ordinary mouse button.

usage: logitech-g400-config.py trace
    Read mouse press/release interrupts from the Logitech-proprietary G400 USB
    interface.  This interface will report DPI+/DPI- presses/releases even with
    ordinary DPI settings.  End the tracing with Ctrl-C.

error: unrecognized argument: -rRATE

**Comment by rprichard** [comment]
The command you want is:

```
python logitech-g400-config.py set -r1000
```

You could also leave off the `python` bit:

```
./logitech-g400-config.py set -r1000
```

You need to unplug the mouse after running `sudo udevadm control --reload-rules` but before running `logitech-g400-config.py`.

When you used `sudo`, though, it looked like the script successfully queried your mouse settings, though, so that's good.

**Comment by rprichard** [comment]
> You need to unplug the mouse after running sudo udevadm control --reload-rules but before running logitech-g400-config.py.

Specifically, do these steps:
1. Verify that you're in the `plugdev` group by running `groups`.
2. Add the `/etc/udev/rules.d/10-logitech-g400-config.rules` file.
3. Run `sudo udevadm control --reload-rules`
4. Unplug the mouse.
5. Plug it back in.
6. Run `./logitech-g400-config.py set -r1000`

You could also replace steps 3-5 with "reboot the computer", but of course, that's inconvenient.

**Comment by phantasyy** [comment]
Oh thanks my bad, seems that I was typing rRATE 1000 instead of r1000. Is this save permantently so I don't need to setup everything again after I start my computer? Also what is that 10-logitech-g400-config.rules file? I don't have it. Also if I wish to disable the DPI buttons do I use -r1000_3600 ?

**Comment by rprichard** [comment]
No, the setting isn't saved permanently.  Personally, I have a script that configures the DPI and polling rates, as well as various xinput settings and `xset m`.  I run the script from my `~/.xsessionrc` file, and I also run it manually if I unplug my mouse between X sessions.

To disable the buttons, you'd use `-d3600_frozen`.

The `10-logitech-g400-config.rules` file is what you need to create so that udev/Linux grants access from the `plugdev` group to your USB mouse.  If your user account isn't in the `plugdev` group, you can add it.
