### ISSUE TITLE
Does not work by default with G400s

### ISSUE THREAD

**Issue by asundell** [rprichard/logitech-g400-config#3]
The G400s mouse performs identically to the G400 in the respects of DPI buttons, and in fact this code work for the G400s as well- however, it requires changing line 45 from
`device_list = hid.enumerate(0x046d, 0xc245)`
to:
`device_list = hid.enumerate(0x046d, 0xc24c)`
to reflect the different device ID. No other changes are necessary.

It would be ideal to have a function by which the program checks both device IDs, and would thus work for both mice with no modifications.

**Comment by rprichard** [comment]
Do the `logitech-g400-config.py set -d3600_frozen` and `logitech-g400-config.py trace` commands also work with the G400s?

 * You can test `-d3600_frozen` on Linux by opening up `xev`, then clicking inside the `xev` window with the DPI+/- buttons.  You should see `ButtonPress`/`ButtonRelease` events.  If you later run `logitech-g400-config.py` without arguments, the DPI level should still be `3600_frozen`.

 * The `logitech-g400-config.py trace` command will show which mouse buttons are pressed, like so:

    ```
    $ ./logitech-g400-config.py trace
    pressed: 0
    pressed:
    pressed: 0
    pressed: 0 1
    pressed: 0 1 2
    pressed: 0 1 2 6
    pressed: 1 2 6
    pressed: 2 6
    pressed: 2
    pressed:
    ```

I also noticed this script for configuring the G400s: https://tnsp.org/~ccr/files/g400s_hack.c.  `g400s_hack.c` only sets the DPI level, not the polling rate.  Apparently the G400s has a "driver mode" flag in the DPI level -- if 0x80 is OR'ed into the DPI level, then the DPI+/- buttons become normal buttons.  I'm guessing it's like the `3600_frozen` mode of the G400, but it works with any DPI setting.

I ran a test just now.  I modified the script to OR 0x80 into the DPI flag, then ran `logitech-g400-config.py set -d<flag>` with my G400.  There was no error, but the DPI level was unchanged, and the mouse's DPI+/- buttons continued changing the DPI level (and not sending ordinary press/release events).

```diff
diff --git a/logitech-g400-config.py b/logitech-g400-config.py
index 816bd42..c6d8a97 100755
--- a/logitech-g400-config.py
+++ b/logitech-g400-config.py
@@ -91,7 +91,7 @@ def do_set_cmd(subargs):
         if arg.startswith("-r") and rate is not None:
             set_var(dev, FEATURE_RATE, rate)
         elif arg.startswith("-d") and dpi is not None:
-            set_var(dev, FEATURE_DPI, dpi)
+            set_var(dev, FEATURE_DPI, dpi | 0x80)
         elif arg == "--help":
             usage(0)
         else:
```
If you applied this change, I'm guessing your DPI+/- buttons *would* become ordinary?

**Comment by rprichard** [comment]
I added a branch to this repo, https://github.com/rprichard/logitech-g400-config/tree/hypothetical_g400s_mode, that ORs in 0x80 for the G400s.  Can you test it?

**Comment by rprichard** [comment]
I haven't heard anything, so I'm going to close this issue.

If someone can verify that the hypothetical_g400s_mode branch works, including the locked/frozen mode and trace mode, then I'll merge the branch.  If someone sends me a G400s mouse (or the $40 for one), then I'll also add support.

**Comment by kremius** [comment]
Unfortunately, seems like the `hypothetical_g400s_mode` branch does not work well for g400s mouse.
However, this solution works https://tnsp.org/~ccr/files/g400s_hack.c

1. `trace` works with all buttons
2. Current mouse config can be fetched normally
```
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 1000
dpi_level: 3600_locked
```
3. Seems like a sampling rate can be changed properly (however, I don't know how to check if it has been changed really).
```
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 1000
dpi_level: 3600_locked
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py set -r500
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 500
dpi_level: 3600_locked

```
4. But DPI cannot be changed:
```
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 500
dpi_level: 3600_locked
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py set -d400
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 500
dpi_level: 3600_locked
```
4. However, aforementioned `g400s_hack` works fine:
```
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 500
dpi_level: 3600_locked
... (another terminal)
kremius@kremius-desktop:~/code/g400s_hack$ sudo ./g400s_hack 400 1
Setting DPI index to 0, driver mode is ENABLED.
Successfully finished.
... (another terminal)
kremius@kremius-desktop:~/code/logitech-g400-config$ sudo ./logitech-g400-config.py
model: G400s
sampling_rate: 500
dpi_level: 400_locked
```
5. I assume the reason is that `g400s_hack` (and windows driver - I have tested it) sends an usb packet which is different from `logitech-g400-config.py` one. This is the working one (from `g400s_hack`):
![right_urb2](https://user-images.githubusercontent.com/3407912/28501822-d0c3deb0-6fec-11e7-90ca-a149f2b3d295.png)
And this one doesn't change anything (from `logitech-g400-config.py`):
![wrong_urb](https://user-images.githubusercontent.com/3407912/28501810-865ae51c-6fec-11e7-8844-5363c2695b4d.png)
6. And some mismatches overall with DPI ids. Windows driver uses ids from `0x83` to `0x87` (5 values). DPI buttons change ids as `7`, `6`, `4`, `3`  (`5` is missing). So overall seems like there are 5 DPI levels in g400s (both `logitech-g400-config.py`/`g400s_hack` do not know about it), but maybe `4` and `5` are same (it feels pretty same). `7` is probably real `3600` then.
DPI buttons can be enabled/disabled properly with `0x80` bit, except `1800`(`5`):
```
kremius@kremius-desktop:~/code/g400s_hack$ sudo ./g400s_hack 1800 0
Setting DPI index to 2, driver mode is DISABLED.
Error writing to USB device! [-9: LIBUSB_ERROR_PIPE / Pipe error]
kremius@kremius-desktop:~/code/g400s_hack$ sudo ./g400s_hack 1800 1
Setting DPI index to 2, driver mode is ENABLED.
Successfully finished.
```

I would be glad to make a patch, but I am not sure if it is possible to create proper USB packet with hidapi. Seems like g400s uses packets which are a little bit different from the hid specification. However, I may be wrong.

**Comment by rprichard** [comment]
I suspect I'm going to want to have a G400s mouse to work with before I publish G400s support on my GitHub account.

With the G400 mouse, the DPI levels were 3, 4, 5, 6, and 7, and AFAICT, 6 and 7 were both 3600, using 7 turned the DPI buttons into ordinary buttons.  I think the G400s has the "driver mode".  It's curious that my script can read and write sample rate and DPI, but it can only modify the sample rate.

If you want to check the sampling rate, the https://gitlab.com/iankelling/evhz project works.  To use the script, move the mouse quickly, and `evhz` will measure how fast samples appear.

Maybe you could fork the repo and use libusb instead of hidapi.  Maybe there are security implications for doing that on some OSs.

**Comment by kremius** [comment]
>If you want to check the sampling rate, the https://gitlab.com/iankelling/evhz project works. To use the script, move the mouse quickly, and evhz will measure how fast samples appear.

Thanks! The polling rate setting works correctly - 125, 250, 500 and 1000 Hz can be set.
